name    'fiddyspence-pe_repo'
version '0.0.1'
source 'https://github.com/fiddyspence/pe_repo'
author 'fiddyspence'
license 'Apache License, Version 2.0'
summary 'Module to create yum/apt repos of Puppet Enterprise'
description 'Module to create yum/apt repos of Puppet Enterprise'
project_page 'https://github.com/fiddyspence/pe_repo'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
